export type SocketEventType =
	| 'createRoom'
	| 'roomCreated'
	| 'joinRoom'
	| 'roomJoined'
	| 'createRoomError'
	| 'joinRoomError'
	| 'leaveRoom'
	| 'leaveRoomError'
	| 'roomLeft'
	| 'roomDeleted'
	| 'roomUpdated'
	| 'connect'
	| 'disconnect'
	| 'error';
